version: '3.9'

services:
  gos-app:
    build:
      context: .
      dockerfile: API/src/GoS.API/Dockerfile
    container_name: gos-app-container
    ports:
      - "43190:43190"
    environment:
      ASPNETCORE_ENVIRONMENT: "Release"
      ASPNETCORE_URLS: "http://+:43190"
      Redis__Enabled: "true"
      Redis__Configuration: "redis:6379"
      Redis__InstanceName: "GoS:"
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:43190/health" ]
      start_period: 10s
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - gos-network

  redis:
    image: redis:latest
    container_name: gos-redis-container
    volumes:
      - gos_redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - gos-network

volumes:
  gos_redis:

networks:
  gos-network:
    driver: bridge